# Config for processing W-Q's volume

name: "somatosensory"
token: "UTUOQJvbbyRFbD_NSnTMig"
db_name: "somatosensory"
db_ssh_forward: True
stem: "/media/data_cifs/"  # "/cifs/data/tserre/CLPS_Serre_Lab/"
# stem: "/cifs/data/tserre/CLPS_Serre_Lab/"
project_directory: "${stem}/projects/prj_connectomics/somatosensory"
file_save_str: "x{}/y{}/z{}/110629_k0725_mag1_x{}_y{}_z{}"
storage:
    raw_img_path: ""
    merge_seg_path: "${project_directory}/merge_mag1_segs"
    seg_path_root: "${project_directory}/mag1_segs"
    mem_path_root: "${project_directory}/mag1_membranes"
    ribbon_path_root: "${project_directory}/mag1_ribbons"
    muller_path_root: "${project_directory}/mag1_mullers"
    seg_path_str: "${project_directory}/mag1_segs/${file_save_str}"
    mem_path_str: "${project_directory}/mag1_membranes/${file_save_str}"
    ribbon_path_str: "${project_directory}/mag1_ribbons/${file_save_str}"
    muller_path_str: "${project_directory}/mag1_mullers/${file_save_str}"
inference:
    membrane_ckpt: "${stem}/connectomics/checkpoints/l3_fgru_constr_berson_0_berson_0_2019_02_16_22_32_22_290193/model_137000.ckpt-137000"
    ffn_ckpt: "${stem}/connectomics/ffn_ckpts/64_fov/ts_1/model.ckpt-1632105"
    ffn_model: "feedback_hgru_v5_3l_notemp_f_v5_ts_1"
    ribbon_ckpt: "${stem}/projects/prj_connectomics/ffn_membrane_v2/synapse_fgru_ckpts/synapse_fgru_v2_ckpts-85000"
    muller_ckpt: "${stem}/projects/prj_connectomics/ffn_membrane_v2/celltype_ckpts/good"
ds:
    path: "${project_directory}"
    img_layer: "color"
    scale: [11.239999771118164, 11.239999771118164, 28]
    vol_shape: [240, 1152, 1152]
    resize_mod: [1.5, 1.5, 1.5]
    force_coord: [2100, 2500, 1500]
    membrane_slice: [240, 384, 384]
    cube_size: [128, 128, 128]  # For creating wkw cubes
    segmentation_layer: "segmentation"

